### ISSUE TITLE
Allow deep linking to a specific user

### ISSUE THREAD

**Issue by watson** [millette/dogfooding#1]
It would be cool, when searching for a given npm user, the URL would change to be unique for that user, eg:

- https://dogfooding-ecrfctojha.now.sh/watson
- https://dogfooding-ecrfctojha.now.sh/?watson
- https://dogfooding-ecrfctojha.now.sh/?user=watson
- or whatever

That would allow you to share/save the link.

**Comment by millette** [comment]
First step will be using ```?``` or ```#``` since it's a static website right now. Thanks for the suggestion!

**Comment by millette** [comment]
Technically, it now works (could be implemented better) but now.sh instances are immutable.
New URL is https://dogfooding-kvjhjzofnk.now.sh/

Search key is author:

* https://dogfooding-kvjhjzofnk.now.sh/?author=watson
* https://dogfooding-kvjhjzofnk.now.sh/?author=millette
